services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION=fanha.local
      - LDAP_DOMAIN=fanha.local
      - LDAP_ADMIN_PASSWORD=password
      - LDAP_ROOT=dc=fanha,dc=local
      - LDAP_TLS=false
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./volumes/ldap-data:/var/lib/ldap
      - ./volumes/ldap-config:/etc/ldap/slapd.d
    networks:
      - cas

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "8080:80"
    depends_on:
      - ldap
    networks:
      - cas

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.1
    environment:
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443"]
    depends_on:
      - ldap
    ports:
      - "8081:7080"
    networks:
      - cas

  moodle_db:
    image: bitnami/mariadb:10.11.11
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_USER=moodle
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=cas_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - ./volumes/moodle_db:/bitnami/mariadb
    networks:
      - cas

  moodle:
    image: bitnami/moodle:4.5-debian-12
    environment:
      - MOODLE_DATABASE_HOST=moodle_db
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=password
      - MOODLE_DATABASE_NAME=cas_moodle
      - MOODLE_USERNAME=yann
      - MOODLE_PASSWORD=password
      - MOODLE_SITE_NAME=CASFANHA
    ports:
      - 8082:8080
    networks:
      - cas
    volumes:
      - ./volumes/moodle/moodle:/bitnami/moodle
      - ./volumes/moodle/moodledata:/bitnami/moodledata
    depends_on:
      - moodle_db

networks:
  cas:
    driver: bridge